name = "CombiCraft S2"
author = "Team Combi-Rings"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b115d5c9c1914fc1dfbd9e77f80b0672e98c764d94f4a1ad3efe335d45bae1f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
