name = "CombiCraft S2"
author = "Team Combi-Rings"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b257589ba3c6edbc7d0031afddf60fb0bc02643ba2221ccd49475ffe189cc672"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
